- hosts: all
  become: 'yes'
  tasks:
    - name: Kubernetes base
      shell:
        cmd: |
          
          touch /home/ansible/rhel-kubernetes-setup.log
          setenforce 0
          sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
          modprobe overlay
          modprobe br_netfilter

          cat > /etc/modules-load.d/k8s.conf << EOF
          overlay
          br_netfilter
          EOF

          cat > /etc/sysctl.d/k8s.conf << EOF
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          EOF
          sysctl --system

          swapoff -a
          sed -e '/swap/s/^/#/g' -i /etc/fstab

          dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

          dnf makecache >> /home/ansible/rhel-kubernetes-setup.log
          dnf install -y containerd.io >> /home/ansible/rhel-kubernetes-setup.log

          sudo mkdir /etc/containerd

          sudo sh -c "containerd config default > /etc/containerd/config.toml"
          sudo sed -i 's/            SystemdCgroup = false/            SystemdCgroup = true/' /etc/containerd/config.toml

          systemctl enable --now containerd.service >> /home/ansible/rhel-kubernetes-setup.log

          sudo systemctl restart containerd.service >> /home/ansible/rhel-kubernetes-setup.log

          cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
          [kubernetes]
          name=Kubernetes
          baseurl=https://pkgs.k8s.io/core:/stable:/v1.28/rpm/
          enabled=1
          gpgcheck=1
          gpgkey=https://pkgs.k8s.io/core:/stable:/v1.28/rpm/repodata/repomd.xml.key
          exclude=kubelet kubeadm kubectl cri-tools kubernetes-cni
          EOF

          dnf makecache >> /home/ansible/rhel-kubernetes-setup.log
          dnf install -y kubelet kubeadm kubectl --disableexcludes=kubernetes >> /home/ansible/rhel-kubernetes-setup.log
          systemctl enable --now kubelet.service >> /home/ansible/rhel-kubernetes-setup.log

      args:
        executable: /bin/bash